GET http://localhost:5233/messages

###
DELETE http://localhost:5233/messages/

###
POST http://localhost:5233/messages
Content-Type: application/json

{
    "MessageUserId":"3",
    "MessageText":"FrontEnd"
}

###
GET http://localhost:5233/users

###
GET http://localhost:5233/rooms

###
GET http://localhost:5233/rooms/1
